server:
    port: 8081

spring:
    application:
        name: user-service
    datasource:
        url: jdbc:postgresql://<db host>:25060/lms-db
        username:
        password:
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        registerWithEureka: true
        fetchRegistry: true

    instance:
        preferIpAddress: true
        instanceId: ${spring.application.name}:${server.port}:${random.value}
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 10
